version: "3.9"

services:
  journify-api:
    image: journify-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./src/Journify.api/.env
    restart: unless-stopped
