services:
  StepManagment-api:
    image: step-managment-api
    build:
      context: ..
      dockerfile: StepManagmentService/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./src/StepManagment.api/.env
    restart: unless-stopped
