apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepmanagment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stepmanagment-api
  template:
    metadata:
      labels:
        app: stepmanagment-api
    spec:
      containers:
      - name: stepmanagment-api
        image: stepmanagment-api:latest
        ports:
        - containerPort: 8080
