apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  user-service
  template:
    metadata:
      labels:
        app:  user-service
    spec:
      containers:
      - name:  user-service
        image: levantisk/journify-user:latest
        ports:
        - containerPort: 8081
        env:
        - name: PostgreSqlConnection
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: PostgreSqlConnection

