apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-service
  template:
    metadata:
      labels:
        app: journey-service
    spec:
      containers:
      - name: journey-service
        image: levantisk/journify-step:latest
        ports:
        - containerPort: 8080
        env:
        - name: PostgreSqlConnection
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: PostgreSqlConnection

